-- INSERTAR USUARIOS
INSERT INTO user (username, password, nombre, apellido, email, fecha_registro, imgurl) VALUES
('bhaskar', '$2a$11$dp4wMyuqYE3KSwIyQmWZFeUb7jCsHAdk7ZhFc0qGw6i5J124imQBi', 'Bhaskar', 'Rathnapur',
 'rbhaskar@gmail.com', '2019-09-10', 'https://i.imgur.com/T0n0PH9.jpg'),
('demo', '$2a$11$.NNQgUXukpCuvB5nG.5XGO/NFOESgfPSqETlg5Pj2paBYmStZiucO', 'demo', 'test', 'demo@demo.com', '2019-09-10', 'https://i.imgur.com/k4k1fOM.png');
-- INSERTAR ROLES
INSERT INTO auth_user_group (username, auth_group) VALUES('bhaskar', 'USER');
INSERT INTO auth_user_group (username, auth_group) VALUES('bhaskar', 'ADMIN');
INSERT INTO auth_user_group (username, auth_group) VALUES('demo', 'USER');
-- INSERTAR PROFESORES
INSERT INTO profesor (nombre, apellido, correo, descripcion, detalle, imgurl) VALUES
( 'Pradeep', 'Kumar', 'pradeepkumar@gmail.com', 'Java Mentor', 'I am a Computer Engineer and I really like to share my knowledge and experience as a programmer. I have worked in numerous companies in Argentina, the United States and Spain. I have 2 years of experience teaching in the following topics: Internet, Java, Microsoft Office, C #, Visual Basic and SQL Server, both in companies and private students.', 'https://bvrit.ac.in/images/faculty/CSE/V-Pradeep-Kumar.jpg'),
( 'Pranitha', 'k', 'pranithak@hotmail.com', 'UX Mentor', '15 years as a professional in the world of private education, teaching in companies (Telefónica, Securitas Direct, Diario As, Marca, Guardia Civil, Stiga, Alten, etc.) and in various schools in Barcelona and Madrid (IDEP, Elisava, Program Acces, RTD, Fomento Nacional del trabajo, Crea Consultoria).', 'https://bvrit.ac.in/images/faculty/CSE/K.Pranitha.jpg'),
( 'Subba Rao', 'k', 'subbaraok@outlook.com', 'Python Mentor', 'Systems Engineer from the Universidad Nacional Mayor de San Marcos with experience in software development and teaching programming classes at basic, intermediate and advanced levels in the languages Python, C / C ++, Java, R, Matlab, Octave and JavaScript and MySQL and PostgreSQL databases.', 'https://bvrit.ac.in/images/faculty/CSE/Dr.K.Subbarao.jpg'),
( 'Ramesh', 'Babu', 'rameshbabuj@yahoo.com', 'Mentor Algorithms ', 'He studied Computer Science, and before that he studied Computer Engineering. I like to teach in my spare time. I feel that my methodology of teaching with basic solid foundations, to be able to later raise the level with intermediate and difficult exercises helps my students to have that evolution and vision for the subject they want to learn. My classes are enjoyable and I am very patient to teach and understandable, no matter what level they have.', 'https://bvrit.ac.in/images/faculty/CSE/J-Ramesh-Babu.jpg'),
('P M ', 'Jyosthna', 'pmjyosthna@hotmail.com', 'HTML Mentor','Systems Engineer with experience in desktop and web software development. With knowledge in technologies such as Java, Php, Javascript, Html, Css. I offer classes at home in the city of Huaraz, to students or anyone who is starting to learn these technologies. It also teaches the use of Php frameworks such as Laravel, Javascript such as Vuejs and Css frameworks such as Bootstrap4.', 'https://bvrit.ac.in/images/faculty/CSE/P.M.Jyothsna.jpg'),
('Md', 'Shabbeer', 'shabbermd@hotmail.com', 'Linux Mentor', 'Network and Communications Engineer, Master with more than 7 years of experience in the field of Computer Security, Network Security, Perimeter Security, Administration of virtualization environments and Administration of Linux - Windows Operating Systems. with the ability to dictate Linux (basic, intermediate, advanced) Windows Server (basic, intermediate advanced), ccna, perimeter security, among others', 'https://bvrit.ac.in/images/faculty/CSE/Md.Shabbir.jpg'),
(' D Abdus ', 'Subhahan', 'abdussubhahand@gmail.com', 'Javascript Mentor ', 'I am a web developer in a company and I have been immersed in the world of programming and computer science since I was 15 years old. I love programming and everything related to the Internet and new technologies, creating things and teaching others. I am almost completely self-taught, so I am going to offer you many of my knowledge so that you can learn more easily and faster than I did and do every day.', 'https://bvrit.ac.in/images/faculty/CSE/D.%20Abdus%20Subhahan.jpg'),
('Jyothirmai', 'D', 'jyothirmaid@outlook.com', 'Database Mentor', 'I am currently working as a consultant for a multinational company EVERIS SAC. In which I am dedicated to analyze and program giving solutions to scenarios or business problems for the client of CLARO. I am passionate about teaching and being able to transmit all my knowledge', 'https://bvrit.ac.in/images/faculty/CSE/D-Jyothirmai.jpg');
-- INSERTAR CURSOS
INSERT INTO curso (nombre, descripcion, profesor_id, detalle, dificultad, url, imgurl) VALUES
( 'Essential Java', 'Java course for beginners', 1, 'If you are looking to learn to program in Java with this course you will obtain knowledge of object-oriented programming through the use and management of the language. Also, with the java course you will develop applications in console, forms and applets, jsp for the internet and many more things.', 'Easy', 'https://www.youtube.com/watch?v=4sZHxFEyEiE&list=PLg9145ptuAihudcXnj8yGBtVWFI6hrrF_', 'https://i.imgur.com/TYsitPM.jpg'),
( 'UX Principles', 'User Experience Course', 2, 'There are plenty of reasons to explain why you should enter the world of User Experience but before you start listing them, do you know what UX is. The UX in Spanish is translated as the user experience. In general terms it is what a person perceives when interacting with a platform. It is considered a good UX when the design, arrangement of elements and usability help make navigation friendly and easy to use.', 'Easy', 'https://www.youtube.com/watch?v=WAi6ixIfdd4&list=PL0X3cJoTgTdNqlc7tdxCioWU-KDKsUKGC', 'https://i.imgur.com/6wp7WIL.jpg'),
( 'Advanced Python', 'Advanced Python Course',3, 'The Advanced Python Course is a 100% online training dedicated to addressing the newest features of the language. With a practical character, it will allow to master the recent improvements of technology in the realization of all kinds of projects.', 'Advanced', 'https://www.youtube.com/watch?v=L_uSbumFspA&list=PLHuhHKl6z1bprks2gYxCj1TWY-7_QRukx', 'https://i.imgur.com/A8lUV2h.jpg'),
( 'Algorithms 101', 'Algorithms Course for beginners',4, 'At the base of every solution in programming, there is an algorithm, in this course we will introduce you to the terminology, forms and design of algorithms. This course is part of our Introduction to Programming specialty, and teaches you how to solve problems with algorithms.', 'Easy', 'https://www.youtube.com/watch?v=YFdXfehe2bo', 'https://i.imgur.com/Xn6TdHy.jpg'),
( 'HTML Basics', 'HTML course for beginners', 5, 'HTML is the language on which the entire web is built and its HTML5 standard completely revolutionized it making the browser the most used program in the world. This course was taught at the Faculty of Systems Engineering of the Universidad Nacional Mayor de San Marcos in Lima, Peru and is offered completely free for you to start your career in web development.', 'Easy', 'https://www.youtube.com/watch?v=rbuYtrNUxg4', 'https://i.imgur.com/gz7yrFb.jpg'),
( 'Advanced HTML', 'Advanced HTML Course', 5, 'Learn HTML5 APIs that will allow you to create web applications with extended capabilities, access to user computer hardware, geolocation, client storage, and more. Learning the APIs that HTML5 introduced will help you expand your understanding of what pages can do.', 'Intermediate', 'https://www.youtube.com/watch?v=QGSxIjjlu3k&list=PLgCfweEKfNwdBW5CBK_XLaD4Rw8sHi2Ur', 'https://i.imgur.com/i9DWWST.jpg'),
( 'Linux Essentials', 'Basic Linux Course', 6, 'Linux is the most widely adopted operating system for server administration on the Internet. Master the management of the operating system, files, permissions, users and packages. Use tools to monitor services and processes. Set scheduled tasks. Configure the security of your server and network to reduce vulnerabilities.', 'Easy', 'https://www.youtube.com/watch?v=lFjmNiPO0cg&list=PLD2wfKpqmxnnFR7H3TfRpdjEHmTpwyLiS', 'https://i.imgur.com/GVTu9L4.jpg'),
( 'Bash Shell', 'Linux Terminal Course', 6, 'All operating systems can be programmed and expressed in commands. For example in Windows it is CMD, in Mac and Linux it is the terminal or the "Shell". The language is known as "Bash". With Bash-Shell you can: manipulate files and folders, run applications, connect an Apps, automate repetitive processes and prepare from your personal computer to a cloud of servers.', 'Intermediate', 'https://www.youtube.com/watch?v=Jp-5bPY5Auk', 'https://i.imgur.com/6LzvoX1.jpg'),
( 'JavaScript Essential Training', 'Basic Javascript Course',7, 'Learn in depth JavaScript, the most used programming language in the world behind the ancestral C and Java, is a language with which you can program in the Frontend of a web page, as well as in the Backend, in addition you can also generate hybrid applications for phones and much more. The course teaches you from the basics, to EcmaScript 5 and EcmaScript 6, the newest versions of Javascript.', 'Easy', 'https://www.youtube.com/watch?v=RqQ1d1qEWlE', 'https://i.imgur.com/5epwqY9.jpg'),
( 'Advanced JavaScript', 'Basic Javascript Course',7, 'Improve your Javascript skills. Learn about Typescript and how you can use it to improve control of your variables. Understand advanced concepts that allow you to propose better solutions in your code. Learn about the DOM APIs and discover how you can better organize your code using design patterns.', 'Intermediate', 'https://www.youtube.com/watch?v=kQ1xYjKFZJ4&list=PLEqCKDlY-B34buE_XNwV8Ri0hoIMP6GhR', 'https://i.imgur.com/vIBF1SA.jpg'),
( 'NodeJS Essential Training', 'Backend course with NodeJS',7, 'Create backend applications using Node.js, Express, and Mongo. Understand how Javascript works on a server and write applications with Node.js. Create an API, manipulate errors, and validate your data with Express. Build tests to find bugs in your code and finally put your application into production in a web service.', 'Advanced', 'https://www.youtube.com/watch?v=fLZ3L9MIXAQ&list=PLpOqH6AE0tNjx0SzNvlsP9-JGJ0zmuFnS', 'https://i.imgur.com/Uy5H4Ze.jpg'),
( 'SQL Essential Training', 'Basic SQL Training Course',8, 'Conoce el mundo de las bases de datos para entender cómo trabajan, cómo se instalan, y las diferencias entre las distintas marcas (SQL Server, MySQL, Oracle, etc.). Aprende lo fundamental para el manejo y manipulación de datos.', 'Facil', 'https://www.youtube.com/watch?v=iOiyJgnN71c&list=PLU8oAlHdN5Bmx-LChV4K3MbHrpZKefNwn', 'https://i.imgur.com/0ol7b83.jpg'),
( 'Advanced SQL', 'Advanced SQL Course',8, 'In this course you will learn the rules that must be considered during the process of developing database models and designing a database, as well as the language necessary for the creation of its objects and manipulation of information from a database manager.', 'Advanced', 'https://www.youtube.com/watch?v=XI5JhpgslL8&list=PLszrufyty21qkFGdF70qfJXXxKwg4MdCC', 'https://i.imgur.com/0jCGazt.jpg'),
( 'MongoDB Essential Training', 'MongoDB Course',8, 'It dominates the foundations of MongoDB, the NoSQL engine that provides high storage capacity. Optimize your processes thanks to the speed of consultation and take advantage of the scalability of this type of databases in your projects.', 'Intermediate', 'https://www.youtube.com/watch?v=lWMemPN9t6Q', 'https://i.imgur.com/qm8cxhp.jpg');
-- INSERTAR MATRICULAS
INSERT INTO matricula (user_id, curso_id, fecha) VALUES ( 1, 3, '2019-10-10' ),
                                                        ( 2, 1, '2019-11-01'),
                                                        ( 2, 4, '2019-11-02' );